---
- name: Ensure the VM volumes do not exist
  script: >
    destroy_virt_volume.sh
    {{ item.name }}
    {{ item.pool | default('default') }}
  with_items: "{{ volumes }}"
  when: item.type | default(libvirt_volume_default_type) == 'volume' or item.type | default(libvirt_volume_default_type) == 'file'
  register: volume_result
  environment: "{{ libvirt_vm_script_env }}"
  changed_when:
    - volume_result is success
    - (volume_result.stdout | from_json).changed | default(True)
  become: yes
